#:schema node_modules/wrangler/config-schema.json
name = "opensensor-auth"
main = "src/index.ts"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]

# Enable workers.dev subdomain
workers_dev = true
